module.exports = {
  env: {
    browser: true,
    node: true,
  },
  plugins: [
    'import',
  ],
  globals: {
    window: false,
    // to allow directly accessing config
    config: false,
  },
  rules: {
    // to make code like `import'views/env'` valid
    'import/no-unresolved': ['error', { ignore: ['views/.*'] }],
    // to allow .es extension
    'import/extensions': ['error', { es: 'never' }],
  },
  settings: {
    'import/resolver': {
      node: {
        // to allow resolving .es and .mjs
        extensions: ['.js', '.jsx', '.es', 'mjs'],
      },
    },
    // poi will modify require paths so that plugins could use poi's dependencies
    'import/core-modules': [
      'electron',
      // following are generated from poi package.json's dependencies
      '@babel/core',
      '@babel/preset-env',
      '@babel/preset-react',
      '@babel/preset-stage-0',
      '@babel/register',
      '@exponent/electron-cookies',
      '@fortawesome/fontawesome-svg-core',
      '@fortawesome/free-brands-svg-icons',
      '@fortawesome/free-regular-svg-icons',
      '@fortawesome/free-solid-svg-icons',
      '@fortawesome/react-fontawesome',
      '@skagami/react-fontawesome',
      'babel-plugin-add-module-exports',
      'babel-plugin-dynamic-import-node',
      'bindings',
      'bluebird',
      'chalk',
      'classnames',
      'coffee-react',
      'coffee-script',
      'create-react-class',
      'cson',
      'electron-log',
      'electron-react-titlebar',
      'electron-updater',
      'fast-memoize',
      'font-awesome',
      'fs-extra',
      'fuse.js',
      'glob',
      'header-case-normalizer',
      'i18n-2',
      'i18next',
      'immutable',
      'json-format',
      'lodash',
      'mime',
      'moment-timezone',
      'mousetrap',
      'node-fetch',
      'npm',
      'pac-proxy-agent',
      'pangu',
      'path-extra',
      'poi-asset-contributor-data',
      'poi-asset-themes',
      'poi-lib-battle',
      'prop-types',
      'react',
      'react-bootstrap',
      'react-dom',
      'react-electron-web-view',
      'react-file-dropzone',
      'react-fontawesome',
      'react-grid-layout',
      'react-i18next',
      'react-redux',
      'react-remarkable',
      'react-resizable-area',
      'react-toastr',
      'react-ultimate-pagination',
      'react-virtualized',
      'reduce-reducers',
      'redux',
      'redux-observers',
      'redux-thunk',
      'request',
      'reselect',
      'semver',
      'socks5-client',
      'socks5-http-client',
      'swf-extract',
      'validate-npm-package-name',
      'wanakana',
      'yargs',
    ],
  },
}
